### PR TITLE
Added support for Carthage

### PR DESCRIPTION
**Pull request by kylejm**

### CODE REVIEW

**Comment by josharian** [comment]
This is the first I've heard of Carthage. I like the idea of a decentralized dependency manager and having card.io support for it seems like a worthwhile goal. However, I'm having a hard time understanding these commits, their purpose, and how they relate to Carthage. Also, I wonder whether this support should be done in the source repo rather than the SDK repo. (Maybe not, given that we have custom build steps, but it's worth double-checking.)

**Comment by kylejm** [comment]
The commit just:

1. Make an Xcode project, which provides build settings and scheme for Cathage to use to build a framework wrapping the headers and the static library
2. Update docs for instructions on using Card.io with Carthage

I'll look in to adding to the source repo – didn't know that existed.

**Comment by josharian** [comment]
@kylejm apologies for the long silence. Where does this stand now?

**Comment by kylejm** [comment]
I haven't added it to the source repo... yet. I may look into it. Feel free to decline this PR if you think it doesn't really make sense for this static library repo :)

**Comment by josharian** [comment]
@kylejm I really would like to see a decentralized dependency manager take off, but yes, I don't think that this is the right place for card.io Carthage support. I'm going to close this, but I've opened #130 so that we do have an open issue for it.

**Comment by kylejm** [comment]
Awesome stuff. Have you made the issue on the SDK repo though and not the source repo?

**Comment by josharian** [comment]
Oops. Yes. Will fix, thanks.

**Pull request closed without merging**
